export const SMTP_REGIONS = [
  "us-east-2", // US East (Ohio)
  "us-east-1", // US East (N. Virginia)
  "us-west-1", // US West (N. California)
  "us-west-2", // US West (Oregon)
  "ap-south-1", // Asia Pacific (Mumbai)
  "ap-northeast-3", // Asia Pacific (Osaka)
  "ap-northeast-2", // Asia Pacific (Seoul)
  "ap-southeast-1", // Asia Pacific (Singapore)
  "ap-southeast-2", // Asia Pacific (Sydney)
  "ap-northeast-1", // Asia Pacific (Tokyo)
  "ca-central-1", // Canada (Central)
  "eu-central-1", // Europe (Frankfurt)
  "eu-west-1", // Europe (Ireland)
  "eu-west-2", // Europe (London)
  "eu-west-3", // Europe (Paris)
  "eu-north-1", // Europe (Stockholm)
  "sa-east-1", // South America (Sao Paulo)
  "us-gov-west-1", // AWS GovCloud (US)
];
